# Database configuration for MySQL in IntelliJ
spring.datasource.url=jdbc:mysql://localhost:3306/shoppingstore
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
logging.level.org.springframework.web.client.RestTemplate=DEBUG
#logging.level.org.springframework.web.client.RestTemplate=DEBUG

# Server configuration
server.servlet.context-path=/shoppingstore

# Additional settings
spring.jpa.open-in-view=false

# AWS Configuration
aws.accessKeyId=AKIA6ELKOAGBQJPXU57V
aws.secretKey=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
aws.region=eu-north-1
aws.s3.bucket=capstone-bucket-cput